"""Generate the requested path + complete source-content handoff, excluding secrets."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
folders = ['app', 'bootstrap', 'config', 'database/factories', 'database/migrations', 'database/seeders', 'resources', 'routes', 'tests', 'docker', 'tools/dataset-sync', '.github']
files = [root / name for name in ['README.md', '.env.example', '.gitignore', '.dockerignore', 'composer.json', 'package.json', 'phpunit.xml', 'vite.config.js', 'Dockerfile', 'compose.yaml', 'artisan', 'public/index.php', 'tools/export-source.py']]
for folder in folders:
    files.extend(p for p in (root / folder).rglob('*') if p.is_file() and 'cache' not in p.parts and '__pycache__' not in p.parts)
output = root / 'docs' / 'SOURCE_CODE.md'
output.parent.mkdir(exist_ok=True)
with output.open('w', encoding='utf-8') as stream:
    stream.write('# Complete application source\n\nGenerated by `python tools/export-source.py`. Dependency lockfiles are delivered separately in the project. No secrets, generated caches, audio, or vendor code are included.\n\n')
    for path in sorted(set(files)):
        suffix = path.suffix.lstrip('.')
        language = {'php': 'php', 'js': 'javascript', 'py': 'python', 'json': 'json', 'css': 'css', 'yml': 'yaml', 'yaml': 'yaml'}.get(suffix, 'text')
        stream.write(f'## `{path.relative_to(root).as_posix()}`\n\n````{language}\n')
        stream.write(path.read_text(encoding='utf-8-sig').rstrip() + '\n````\n\n')
print(output)
